# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mir100_client
from models.post_position_transition_lists import PostPositionTransitionLists  # noqa: E501
from mir100_client.rest import ApiException


class TestPostPositionTransitionLists(unittest.TestCase):
    """PostPositionTransitionLists unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostPositionTransitionLists(self):
        """Test PostPositionTransitionLists"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mir100_client.models.post_position_transition_lists.PostPositionTransitionLists()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
