# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mir100_client
from models.get_factory_reset import GetFactoryReset  # noqa: E501
from mir100_client.rest import ApiException


class TestGetFactoryReset(unittest.TestCase):
    """GetFactoryReset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFactoryReset(self):
        """Test GetFactoryReset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mir100_client.models.get_factory_reset.GetFactoryReset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
