# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Cart(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height': 'float',
        'id': 'float',
        'length': 'float',
        'offset_locked_wheels': 'float',
        'width': 'float'
    }

    attribute_map = {
        'height': 'height',
        'id': 'id',
        'length': 'length',
        'offset_locked_wheels': 'offset_locked_wheels',
        'width': 'width'
    }

    def __init__(self, height=None, id=None, length=None, offset_locked_wheels=None, width=None):  # noqa: E501
        """Cart - a model defined in Swagger"""  # noqa: E501
        self._height = None
        self._id = None
        self._length = None
        self._offset_locked_wheels = None
        self._width = None
        self.discriminator = None
        if height is not None:
            self.height = height
        if id is not None:
            self.id = id
        if length is not None:
            self.length = length
        if offset_locked_wheels is not None:
            self.offset_locked_wheels = offset_locked_wheels
        if width is not None:
            self.width = width

    @property
    def height(self):
        """Gets the height of this Cart.  # noqa: E501

        The height of the attached trolley  # noqa: E501

        :return: The height of this Cart.  # noqa: E501
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Cart.

        The height of the attached trolley  # noqa: E501

        :param height: The height of this Cart.  # noqa: E501
        :type: float
        """

        self._height = height

    @property
    def id(self):
        """Gets the id of this Cart.  # noqa: E501

        The id of the attached trolley  # noqa: E501

        :return: The id of this Cart.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Cart.

        The id of the attached trolley  # noqa: E501

        :param id: The id of this Cart.  # noqa: E501
        :type: float
        """

        self._id = id

    @property
    def length(self):
        """Gets the length of this Cart.  # noqa: E501

        The length of the attached trolley  # noqa: E501

        :return: The length of this Cart.  # noqa: E501
        :rtype: float
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this Cart.

        The length of the attached trolley  # noqa: E501

        :param length: The length of this Cart.  # noqa: E501
        :type: float
        """

        self._length = length

    @property
    def offset_locked_wheels(self):
        """Gets the offset_locked_wheels of this Cart.  # noqa: E501

        The distance from front of the attached trolley to the locked wheels  # noqa: E501

        :return: The offset_locked_wheels of this Cart.  # noqa: E501
        :rtype: float
        """
        return self._offset_locked_wheels

    @offset_locked_wheels.setter
    def offset_locked_wheels(self, offset_locked_wheels):
        """Sets the offset_locked_wheels of this Cart.

        The distance from front of the attached trolley to the locked wheels  # noqa: E501

        :param offset_locked_wheels: The offset_locked_wheels of this Cart.  # noqa: E501
        :type: float
        """

        self._offset_locked_wheels = offset_locked_wheels

    @property
    def width(self):
        """Gets the width of this Cart.  # noqa: E501

        The width of the attached trolley  # noqa: E501

        :return: The width of this Cart.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this Cart.

        The width of the attached trolley  # noqa: E501

        :param width: The width of this Cart.  # noqa: E501
        :type: float
        """

        self._width = width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Cart, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Cart):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
