# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetShelfType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bar_distance': 'float',
        'bar_length': 'float',
        'created_by': 'str',
        'created_by_id': 'str',
        'guid': 'str',
        'height': 'float',
        'length': 'float',
        'name': 'str',
        'offset_x': 'float',
        'offset_y': 'float',
        'width': 'float'
    }

    attribute_map = {
        'bar_distance': 'bar_distance',
        'bar_length': 'bar_length',
        'created_by': 'created_by',
        'created_by_id': 'created_by_id',
        'guid': 'guid',
        'height': 'height',
        'length': 'length',
        'name': 'name',
        'offset_x': 'offset_x',
        'offset_y': 'offset_y',
        'width': 'width'
    }

    def __init__(self, bar_distance=None, bar_length=None, created_by=None, created_by_id=None, guid=None, height=None, length=None, name=None, offset_x=None, offset_y=None, width=None):  # noqa: E501
        """GetShelfType - a model defined in Swagger"""  # noqa: E501
        self._bar_distance = None
        self._bar_length = None
        self._created_by = None
        self._created_by_id = None
        self._guid = None
        self._height = None
        self._length = None
        self._name = None
        self._offset_x = None
        self._offset_y = None
        self._width = None
        self.discriminator = None
        if bar_distance is not None:
            self.bar_distance = bar_distance
        if bar_length is not None:
            self.bar_length = bar_length
        if created_by is not None:
            self.created_by = created_by
        if created_by_id is not None:
            self.created_by_id = created_by_id
        if guid is not None:
            self.guid = guid
        if height is not None:
            self.height = height
        if length is not None:
            self.length = length
        if name is not None:
            self.name = name
        if offset_x is not None:
            self.offset_x = offset_x
        if offset_y is not None:
            self.offset_y = offset_y
        if width is not None:
            self.width = width

    @property
    def bar_distance(self):
        """Gets the bar_distance of this GetShelfType.  # noqa: E501

        The distance between the side bars of shelves of this type  # noqa: E501

        :return: The bar_distance of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._bar_distance

    @bar_distance.setter
    def bar_distance(self, bar_distance):
        """Sets the bar_distance of this GetShelfType.

        The distance between the side bars of shelves of this type  # noqa: E501

        :param bar_distance: The bar_distance of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._bar_distance = bar_distance

    @property
    def bar_length(self):
        """Gets the bar_length of this GetShelfType.  # noqa: E501

        The length of the side bars of shelves of this type  # noqa: E501

        :return: The bar_length of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._bar_length

    @bar_length.setter
    def bar_length(self, bar_length):
        """Sets the bar_length of this GetShelfType.

        The length of the side bars of shelves of this type  # noqa: E501

        :param bar_length: The bar_length of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._bar_length = bar_length

    @property
    def created_by(self):
        """Gets the created_by of this GetShelfType.  # noqa: E501

        The url to the description of the type of this position  # noqa: E501

        :return: The created_by of this GetShelfType.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this GetShelfType.

        The url to the description of the type of this position  # noqa: E501

        :param created_by: The created_by of this GetShelfType.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def created_by_id(self):
        """Gets the created_by_id of this GetShelfType.  # noqa: E501

        The global id of the user who created this entry  # noqa: E501

        :return: The created_by_id of this GetShelfType.  # noqa: E501
        :rtype: str
        """
        return self._created_by_id

    @created_by_id.setter
    def created_by_id(self, created_by_id):
        """Sets the created_by_id of this GetShelfType.

        The global id of the user who created this entry  # noqa: E501

        :param created_by_id: The created_by_id of this GetShelfType.  # noqa: E501
        :type: str
        """

        self._created_by_id = created_by_id

    @property
    def guid(self):
        """Gets the guid of this GetShelfType.  # noqa: E501

        The global id unique across robots that identifies this shelf type  # noqa: E501

        :return: The guid of this GetShelfType.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GetShelfType.

        The global id unique across robots that identifies this shelf type  # noqa: E501

        :param guid: The guid of this GetShelfType.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def height(self):
        """Gets the height of this GetShelfType.  # noqa: E501

        The height of shelves of this type  # noqa: E501

        :return: The height of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this GetShelfType.

        The height of shelves of this type  # noqa: E501

        :param height: The height of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._height = height

    @property
    def length(self):
        """Gets the length of this GetShelfType.  # noqa: E501

        The length of shelves of this type  # noqa: E501

        :return: The length of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this GetShelfType.

        The length of shelves of this type  # noqa: E501

        :param length: The length of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._length = length

    @property
    def name(self):
        """Gets the name of this GetShelfType.  # noqa: E501

        The name of the shelf type  # noqa: E501

        :return: The name of this GetShelfType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetShelfType.

        The name of the shelf type  # noqa: E501

        :param name: The name of this GetShelfType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def offset_x(self):
        """Gets the offset_x of this GetShelfType.  # noqa: E501

        The offset in the x-coordinate of shelf of this type  # noqa: E501

        :return: The offset_x of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._offset_x

    @offset_x.setter
    def offset_x(self, offset_x):
        """Sets the offset_x of this GetShelfType.

        The offset in the x-coordinate of shelf of this type  # noqa: E501

        :param offset_x: The offset_x of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._offset_x = offset_x

    @property
    def offset_y(self):
        """Gets the offset_y of this GetShelfType.  # noqa: E501

        The offset in the y-coordinate of shelves of this type  # noqa: E501

        :return: The offset_y of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._offset_y

    @offset_y.setter
    def offset_y(self, offset_y):
        """Sets the offset_y of this GetShelfType.

        The offset in the y-coordinate of shelves of this type  # noqa: E501

        :param offset_y: The offset_y of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._offset_y = offset_y

    @property
    def width(self):
        """Gets the width of this GetShelfType.  # noqa: E501

        The width of shelves of this type  # noqa: E501

        :return: The width of this GetShelfType.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this GetShelfType.

        The width of shelves of this type  # noqa: E501

        :param width: The width of this GetShelfType.  # noqa: E501
        :type: float
        """

        self._width = width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetShelfType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetShelfType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
