# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetAreaActionDefinitions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_type': 'str',
        'action_type_id': 'int',
        'help': 'str',
        'limit': 'int',
        'name': 'str',
        'parameters': 'str'
    }

    attribute_map = {
        'action_type': 'action_type',
        'action_type_id': 'action_type_id',
        'help': 'help',
        'limit': 'limit',
        'name': 'name',
        'parameters': 'parameters'
    }

    def __init__(self, action_type=None, action_type_id=None, help=None, limit=None, name=None, parameters=None):  # noqa: E501
        """GetAreaActionDefinitions - a model defined in Swagger"""  # noqa: E501
        self._action_type = None
        self._action_type_id = None
        self._help = None
        self._limit = None
        self._name = None
        self._parameters = None
        self.discriminator = None
        if action_type is not None:
            self.action_type = action_type
        if action_type_id is not None:
            self.action_type_id = action_type_id
        if help is not None:
            self.help = help
        if limit is not None:
            self.limit = limit
        if name is not None:
            self.name = name
        if parameters is not None:
            self.parameters = parameters

    @property
    def action_type(self):
        """Gets the action_type of this GetAreaActionDefinitions.  # noqa: E501

        A name associated with this area action  # noqa: E501

        :return: The action_type of this GetAreaActionDefinitions.  # noqa: E501
        :rtype: str
        """
        return self._action_type

    @action_type.setter
    def action_type(self, action_type):
        """Sets the action_type of this GetAreaActionDefinitions.

        A name associated with this area action  # noqa: E501

        :param action_type: The action_type of this GetAreaActionDefinitions.  # noqa: E501
        :type: str
        """

        self._action_type = action_type

    @property
    def action_type_id(self):
        """Gets the action_type_id of this GetAreaActionDefinitions.  # noqa: E501

        The type of area action  # noqa: E501

        :return: The action_type_id of this GetAreaActionDefinitions.  # noqa: E501
        :rtype: int
        """
        return self._action_type_id

    @action_type_id.setter
    def action_type_id(self, action_type_id):
        """Sets the action_type_id of this GetAreaActionDefinitions.

        The type of area action  # noqa: E501

        :param action_type_id: The action_type_id of this GetAreaActionDefinitions.  # noqa: E501
        :type: int
        """

        self._action_type_id = action_type_id

    @property
    def help(self):
        """Gets the help of this GetAreaActionDefinitions.  # noqa: E501

        A description of this action  # noqa: E501

        :return: The help of this GetAreaActionDefinitions.  # noqa: E501
        :rtype: str
        """
        return self._help

    @help.setter
    def help(self, help):
        """Sets the help of this GetAreaActionDefinitions.

        A description of this action  # noqa: E501

        :param help: The help of this GetAreaActionDefinitions.  # noqa: E501
        :type: str
        """

        self._help = help

    @property
    def limit(self):
        """Gets the limit of this GetAreaActionDefinitions.  # noqa: E501

        The amount of actions of this type we can add.  # noqa: E501

        :return: The limit of this GetAreaActionDefinitions.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this GetAreaActionDefinitions.

        The amount of actions of this type we can add.  # noqa: E501

        :param limit: The limit of this GetAreaActionDefinitions.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def name(self):
        """Gets the name of this GetAreaActionDefinitions.  # noqa: E501

        A nice name associated with this area action  # noqa: E501

        :return: The name of this GetAreaActionDefinitions.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetAreaActionDefinitions.

        A nice name associated with this area action  # noqa: E501

        :param name: The name of this GetAreaActionDefinitions.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parameters(self):
        """Gets the parameters of this GetAreaActionDefinitions.  # noqa: E501


        :return: The parameters of this GetAreaActionDefinitions.  # noqa: E501
        :rtype: str
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this GetAreaActionDefinitions.


        :param parameters: The parameters of this GetAreaActionDefinitions.  # noqa: E501
        :type: str
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetAreaActionDefinitions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetAreaActionDefinitions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
