# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetSoftwareLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'str',
        'end_time': 'datetime',
        '_from': 'str',
        'guid': 'str',
        'message': 'str',
        'start_time': 'datetime',
        'state': 'str',
        'to': 'str'
    }

    attribute_map = {
        'action': 'action',
        'end_time': 'end_time',
        '_from': 'from',
        'guid': 'guid',
        'message': 'message',
        'start_time': 'start_time',
        'state': 'state',
        'to': 'to'
    }

    def __init__(self, action=None, end_time=None, _from=None, guid=None, message=None, start_time=None, state=None, to=None):  # noqa: E501
        """GetSoftwareLog - a model defined in Swagger"""  # noqa: E501
        self._action = None
        self._end_time = None
        self.__from = None
        self._guid = None
        self._message = None
        self._start_time = None
        self._state = None
        self._to = None
        self.discriminator = None
        if action is not None:
            self.action = action
        if end_time is not None:
            self.end_time = end_time
        if _from is not None:
            self._from = _from
        if guid is not None:
            self.guid = guid
        if message is not None:
            self.message = message
        if start_time is not None:
            self.start_time = start_time
        if state is not None:
            self.state = state
        if to is not None:
            self.to = to

    @property
    def action(self):
        """Gets the action of this GetSoftwareLog.  # noqa: E501

        The action performed (upgrade/restore)  # noqa: E501

        :return: The action of this GetSoftwareLog.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this GetSoftwareLog.

        The action performed (upgrade/restore)  # noqa: E501

        :param action: The action of this GetSoftwareLog.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def end_time(self):
        """Gets the end_time of this GetSoftwareLog.  # noqa: E501

        The end time of the upgrade  # noqa: E501

        :return: The end_time of this GetSoftwareLog.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this GetSoftwareLog.

        The end time of the upgrade  # noqa: E501

        :param end_time: The end_time of this GetSoftwareLog.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def _from(self):
        """Gets the _from of this GetSoftwareLog.  # noqa: E501

        The software version upgrading from  # noqa: E501

        :return: The _from of this GetSoftwareLog.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this GetSoftwareLog.

        The software version upgrading from  # noqa: E501

        :param _from: The _from of this GetSoftwareLog.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def guid(self):
        """Gets the guid of this GetSoftwareLog.  # noqa: E501

        The guid of upgrade entry  # noqa: E501

        :return: The guid of this GetSoftwareLog.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GetSoftwareLog.

        The guid of upgrade entry  # noqa: E501

        :param guid: The guid of this GetSoftwareLog.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def message(self):
        """Gets the message of this GetSoftwareLog.  # noqa: E501

        The status message from upgrade  # noqa: E501

        :return: The message of this GetSoftwareLog.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this GetSoftwareLog.

        The status message from upgrade  # noqa: E501

        :param message: The message of this GetSoftwareLog.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def start_time(self):
        """Gets the start_time of this GetSoftwareLog.  # noqa: E501

        The start time of the upgrade  # noqa: E501

        :return: The start_time of this GetSoftwareLog.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this GetSoftwareLog.

        The start time of the upgrade  # noqa: E501

        :param start_time: The start_time of this GetSoftwareLog.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def state(self):
        """Gets the state of this GetSoftwareLog.  # noqa: E501

        The state of the upgrade (succeeded/failed/started  # noqa: E501

        :return: The state of this GetSoftwareLog.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetSoftwareLog.

        The state of the upgrade (succeeded/failed/started  # noqa: E501

        :param state: The state of this GetSoftwareLog.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def to(self):
        """Gets the to of this GetSoftwareLog.  # noqa: E501

        The software version upgrading to  # noqa: E501

        :return: The to of this GetSoftwareLog.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this GetSoftwareLog.

        The software version upgrading to  # noqa: E501

        :param to: The to of this GetSoftwareLog.  # noqa: E501
        :type: str
        """

        self._to = to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSoftwareLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSoftwareLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
