# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default': 'str',
        'id': 'int',
        'name': 'str',
        'parent_name': 'str',
        'url': 'str',
        'value': 'str'
    }

    attribute_map = {
        'default': 'default',
        'id': 'id',
        'name': 'name',
        'parent_name': 'parent_name',
        'url': 'url',
        'value': 'value'
    }

    def __init__(self, default=None, id=None, name=None, parent_name=None, url=None, value=None):  # noqa: E501
        """GetSettings - a model defined in Swagger"""  # noqa: E501
        self._default = None
        self._id = None
        self._name = None
        self._parent_name = None
        self._url = None
        self._value = None
        self.discriminator = None
        if default is not None:
            self.default = default
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if parent_name is not None:
            self.parent_name = parent_name
        if url is not None:
            self.url = url
        if value is not None:
            self.value = value

    @property
    def default(self):
        """Gets the default of this GetSettings.  # noqa: E501


        :return: The default of this GetSettings.  # noqa: E501
        :rtype: str
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this GetSettings.


        :param default: The default of this GetSettings.  # noqa: E501
        :type: str
        """

        self._default = default

    @property
    def id(self):
        """Gets the id of this GetSettings.  # noqa: E501


        :return: The id of this GetSettings.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetSettings.


        :param id: The id of this GetSettings.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GetSettings.  # noqa: E501


        :return: The name of this GetSettings.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetSettings.


        :param name: The name of this GetSettings.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parent_name(self):
        """Gets the parent_name of this GetSettings.  # noqa: E501


        :return: The parent_name of this GetSettings.  # noqa: E501
        :rtype: str
        """
        return self._parent_name

    @parent_name.setter
    def parent_name(self, parent_name):
        """Sets the parent_name of this GetSettings.


        :param parent_name: The parent_name of this GetSettings.  # noqa: E501
        :type: str
        """

        self._parent_name = parent_name

    @property
    def url(self):
        """Gets the url of this GetSettings.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetSettings.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetSettings.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetSettings.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def value(self):
        """Gets the value of this GetSettings.  # noqa: E501


        :return: The value of this GetSettings.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this GetSettings.


        :param value: The value of this GetSettings.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
