# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetCarts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cart_calibration': 'str',
        'cart_type': 'str',
        'guid': 'str',
        'name': 'str',
        'url': 'str'
    }

    attribute_map = {
        'cart_calibration': 'cart_calibration',
        'cart_type': 'cart_type',
        'guid': 'guid',
        'name': 'name',
        'url': 'url'
    }

    def __init__(self, cart_calibration=None, cart_type=None, guid=None, name=None, url=None):  # noqa: E501
        """GetCarts - a model defined in Swagger"""  # noqa: E501
        self._cart_calibration = None
        self._cart_type = None
        self._guid = None
        self._name = None
        self._url = None
        self.discriminator = None
        if cart_calibration is not None:
            self.cart_calibration = cart_calibration
        if cart_type is not None:
            self.cart_type = cart_type
        if guid is not None:
            self.guid = guid
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url

    @property
    def cart_calibration(self):
        """Gets the cart_calibration of this GetCarts.  # noqa: E501

        The url to the calibration of this cart  # noqa: E501

        :return: The cart_calibration of this GetCarts.  # noqa: E501
        :rtype: str
        """
        return self._cart_calibration

    @cart_calibration.setter
    def cart_calibration(self, cart_calibration):
        """Sets the cart_calibration of this GetCarts.

        The url to the calibration of this cart  # noqa: E501

        :param cart_calibration: The cart_calibration of this GetCarts.  # noqa: E501
        :type: str
        """

        self._cart_calibration = cart_calibration

    @property
    def cart_type(self):
        """Gets the cart_type of this GetCarts.  # noqa: E501

        The url to the type of this cart  # noqa: E501

        :return: The cart_type of this GetCarts.  # noqa: E501
        :rtype: str
        """
        return self._cart_type

    @cart_type.setter
    def cart_type(self, cart_type):
        """Sets the cart_type of this GetCarts.

        The url to the type of this cart  # noqa: E501

        :param cart_type: The cart_type of this GetCarts.  # noqa: E501
        :type: str
        """

        self._cart_type = cart_type

    @property
    def guid(self):
        """Gets the guid of this GetCarts.  # noqa: E501

        The global id unique across robots that identifies this cart  # noqa: E501

        :return: The guid of this GetCarts.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GetCarts.

        The global id unique across robots that identifies this cart  # noqa: E501

        :param guid: The guid of this GetCarts.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def name(self):
        """Gets the name of this GetCarts.  # noqa: E501

        The name of the cart  # noqa: E501

        :return: The name of this GetCarts.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetCarts.

        The name of the cart  # noqa: E501

        :param name: The name of this GetCarts.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this GetCarts.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetCarts.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetCarts.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetCarts.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetCarts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCarts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
