# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetSession(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'created_by': 'str',
        'created_by_id': 'str',
        'description': 'str',
        'export': 'str',
        'guid': 'str',
        'maps': 'str',
        'name': 'str'
    }

    attribute_map = {
        'active': 'active',
        'created_by': 'created_by',
        'created_by_id': 'created_by_id',
        'description': 'description',
        'export': 'export',
        'guid': 'guid',
        'maps': 'maps',
        'name': 'name'
    }

    def __init__(self, active=None, created_by=None, created_by_id=None, description=None, export=None, guid=None, maps=None, name=None):  # noqa: E501
        """GetSession - a model defined in Swagger"""  # noqa: E501
        self._active = None
        self._created_by = None
        self._created_by_id = None
        self._description = None
        self._export = None
        self._guid = None
        self._maps = None
        self._name = None
        self.discriminator = None
        if active is not None:
            self.active = active
        if created_by is not None:
            self.created_by = created_by
        if created_by_id is not None:
            self.created_by_id = created_by_id
        if description is not None:
            self.description = description
        if export is not None:
            self.export = export
        if guid is not None:
            self.guid = guid
        if maps is not None:
            self.maps = maps
        if name is not None:
            self.name = name

    @property
    def active(self):
        """Gets the active of this GetSession.  # noqa: E501

        Boolean indicating whether the session is the active session in the fleet  # noqa: E501

        :return: The active of this GetSession.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this GetSession.

        Boolean indicating whether the session is the active session in the fleet  # noqa: E501

        :param active: The active of this GetSession.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def created_by(self):
        """Gets the created_by of this GetSession.  # noqa: E501

        The url to the description of the type of this position  # noqa: E501

        :return: The created_by of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this GetSession.

        The url to the description of the type of this position  # noqa: E501

        :param created_by: The created_by of this GetSession.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def created_by_id(self):
        """Gets the created_by_id of this GetSession.  # noqa: E501

        The global id of the user who created this entry  # noqa: E501

        :return: The created_by_id of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._created_by_id

    @created_by_id.setter
    def created_by_id(self, created_by_id):
        """Sets the created_by_id of this GetSession.

        The global id of the user who created this entry  # noqa: E501

        :param created_by_id: The created_by_id of this GetSession.  # noqa: E501
        :type: str
        """

        self._created_by_id = created_by_id

    @property
    def description(self):
        """Gets the description of this GetSession.  # noqa: E501

        A possible description of the area  # noqa: E501

        :return: The description of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GetSession.

        A possible description of the area  # noqa: E501

        :param description: The description of this GetSession.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def export(self):
        """Gets the export of this GetSession.  # noqa: E501


        :return: The export of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._export

    @export.setter
    def export(self, export):
        """Sets the export of this GetSession.


        :param export: The export of this GetSession.  # noqa: E501
        :type: str
        """

        self._export = export

    @property
    def guid(self):
        """Gets the guid of this GetSession.  # noqa: E501

        The global id unique across robots that identifies this area  # noqa: E501

        :return: The guid of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GetSession.

        The global id unique across robots that identifies this area  # noqa: E501

        :param guid: The guid of this GetSession.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def maps(self):
        """Gets the maps of this GetSession.  # noqa: E501

        The url to the list of maps that is in this area  # noqa: E501

        :return: The maps of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._maps

    @maps.setter
    def maps(self, maps):
        """Sets the maps of this GetSession.

        The url to the list of maps that is in this area  # noqa: E501

        :param maps: The maps of this GetSession.  # noqa: E501
        :type: str
        """

        self._maps = maps

    @property
    def name(self):
        """Gets the name of this GetSession.  # noqa: E501

        The name of the area  # noqa: E501

        :return: The name of this GetSession.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetSession.

        The name of the area  # noqa: E501

        :param name: The name of this GetSession.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSession, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSession):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
