# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetUsersAuth(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expiration_time': 'datetime',
        'ip': 'str',
        'login_time': 'datetime',
        'token': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'expiration_time': 'expiration_time',
        'ip': 'ip',
        'login_time': 'login_time',
        'token': 'token',
        'user_id': 'user_id'
    }

    def __init__(self, expiration_time=None, ip=None, login_time=None, token=None, user_id=None):  # noqa: E501
        """GetUsersAuth - a model defined in Swagger"""  # noqa: E501
        self._expiration_time = None
        self._ip = None
        self._login_time = None
        self._token = None
        self._user_id = None
        self.discriminator = None
        if expiration_time is not None:
            self.expiration_time = expiration_time
        if ip is not None:
            self.ip = ip
        if login_time is not None:
            self.login_time = login_time
        if token is not None:
            self.token = token
        if user_id is not None:
            self.user_id = user_id

    @property
    def expiration_time(self):
        """Gets the expiration_time of this GetUsersAuth.  # noqa: E501


        :return: The expiration_time of this GetUsersAuth.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_time

    @expiration_time.setter
    def expiration_time(self, expiration_time):
        """Sets the expiration_time of this GetUsersAuth.


        :param expiration_time: The expiration_time of this GetUsersAuth.  # noqa: E501
        :type: datetime
        """

        self._expiration_time = expiration_time

    @property
    def ip(self):
        """Gets the ip of this GetUsersAuth.  # noqa: E501


        :return: The ip of this GetUsersAuth.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this GetUsersAuth.


        :param ip: The ip of this GetUsersAuth.  # noqa: E501
        :type: str
        """

        self._ip = ip

    @property
    def login_time(self):
        """Gets the login_time of this GetUsersAuth.  # noqa: E501


        :return: The login_time of this GetUsersAuth.  # noqa: E501
        :rtype: datetime
        """
        return self._login_time

    @login_time.setter
    def login_time(self, login_time):
        """Sets the login_time of this GetUsersAuth.


        :param login_time: The login_time of this GetUsersAuth.  # noqa: E501
        :type: datetime
        """

        self._login_time = login_time

    @property
    def token(self):
        """Gets the token of this GetUsersAuth.  # noqa: E501


        :return: The token of this GetUsersAuth.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this GetUsersAuth.


        :param token: The token of this GetUsersAuth.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def user_id(self):
        """Gets the user_id of this GetUsersAuth.  # noqa: E501


        :return: The user_id of this GetUsersAuth.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this GetUsersAuth.


        :param user_id: The user_id of this GetUsersAuth.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetUsersAuth, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetUsersAuth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
