# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetMissionQueues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'state': 'str',
        'url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'state': 'state',
        'url': 'url'
    }

    def __init__(self, id=None, state=None, url=None):  # noqa: E501
        """GetMissionQueues - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._state = None
        self._url = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if state is not None:
            self.state = state
        if url is not None:
            self.url = url

    @property
    def id(self):
        """Gets the id of this GetMissionQueues.  # noqa: E501

        The id of the mission queue entry  # noqa: E501

        :return: The id of this GetMissionQueues.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetMissionQueues.

        The id of the mission queue entry  # noqa: E501

        :param id: The id of this GetMissionQueues.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def state(self):
        """Gets the state of this GetMissionQueues.  # noqa: E501

        The end state after the mission was executed  # noqa: E501

        :return: The state of this GetMissionQueues.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetMissionQueues.

        The end state after the mission was executed  # noqa: E501

        :param state: The state of this GetMissionQueues.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def url(self):
        """Gets the url of this GetMissionQueues.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetMissionQueues.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetMissionQueues.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetMissionQueues.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMissionQueues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMissionQueues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
