# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetPositionType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hidden': 'bool',
        'id': 'int',
        'name': 'str',
        'reachable_for_robot': 'bool'
    }

    attribute_map = {
        'hidden': 'hidden',
        'id': 'id',
        'name': 'name',
        'reachable_for_robot': 'reachable_for_robot'
    }

    def __init__(self, hidden=None, id=None, name=None, reachable_for_robot=None):  # noqa: E501
        """GetPositionType - a model defined in Swagger"""  # noqa: E501
        self._hidden = None
        self._id = None
        self._name = None
        self._reachable_for_robot = None
        self.discriminator = None
        if hidden is not None:
            self.hidden = hidden
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if reachable_for_robot is not None:
            self.reachable_for_robot = reachable_for_robot

    @property
    def hidden(self):
        """Gets the hidden of this GetPositionType.  # noqa: E501

        False if the position is not created by the user  # noqa: E501

        :return: The hidden of this GetPositionType.  # noqa: E501
        :rtype: bool
        """
        return self._hidden

    @hidden.setter
    def hidden(self, hidden):
        """Sets the hidden of this GetPositionType.

        False if the position is not created by the user  # noqa: E501

        :param hidden: The hidden of this GetPositionType.  # noqa: E501
        :type: bool
        """

        self._hidden = hidden

    @property
    def id(self):
        """Gets the id of this GetPositionType.  # noqa: E501

        Unique id for the position type  # noqa: E501

        :return: The id of this GetPositionType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetPositionType.

        Unique id for the position type  # noqa: E501

        :param id: The id of this GetPositionType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GetPositionType.  # noqa: E501

        Name of the position type  # noqa: E501

        :return: The name of this GetPositionType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetPositionType.

        Name of the position type  # noqa: E501

        :param name: The name of this GetPositionType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def reachable_for_robot(self):
        """Gets the reachable_for_robot of this GetPositionType.  # noqa: E501

        True if the robot can actually go to that position  # noqa: E501

        :return: The reachable_for_robot of this GetPositionType.  # noqa: E501
        :rtype: bool
        """
        return self._reachable_for_robot

    @reachable_for_robot.setter
    def reachable_for_robot(self, reachable_for_robot):
        """Sets the reachable_for_robot of this GetPositionType.

        True if the robot can actually go to that position  # noqa: E501

        :param reachable_for_robot: The reachable_for_robot of this GetPositionType.  # noqa: E501
        :type: bool
        """

        self._reachable_for_robot = reachable_for_robot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetPositionType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetPositionType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
