# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetPosDockingOffsets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'position': 'str',
        'url': 'str'
    }

    attribute_map = {
        'guid': 'guid',
        'position': 'position',
        'url': 'url'
    }

    def __init__(self, guid=None, position=None, url=None):  # noqa: E501
        """GetPosDockingOffsets - a model defined in Swagger"""  # noqa: E501
        self._guid = None
        self._position = None
        self._url = None
        self.discriminator = None
        if guid is not None:
            self.guid = guid
        if position is not None:
            self.position = position
        if url is not None:
            self.url = url

    @property
    def guid(self):
        """Gets the guid of this GetPosDockingOffsets.  # noqa: E501

        The global id unique across robots that identifies this docking offset  # noqa: E501

        :return: The guid of this GetPosDockingOffsets.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GetPosDockingOffsets.

        The global id unique across robots that identifies this docking offset  # noqa: E501

        :param guid: The guid of this GetPosDockingOffsets.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def position(self):
        """Gets the position of this GetPosDockingOffsets.  # noqa: E501

        The url to the position  # noqa: E501

        :return: The position of this GetPosDockingOffsets.  # noqa: E501
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this GetPosDockingOffsets.

        The url to the position  # noqa: E501

        :param position: The position of this GetPosDockingOffsets.  # noqa: E501
        :type: str
        """

        self._position = position

    @property
    def url(self):
        """Gets the url of this GetPosDockingOffsets.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetPosDockingOffsets.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetPosDockingOffsets.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetPosDockingOffsets.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetPosDockingOffsets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetPosDockingOffsets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
