# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetHookBrake(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'braked': 'bool',
        'state': 'int',
        'state_string': 'str'
    }

    attribute_map = {
        'braked': 'braked',
        'state': 'state',
        'state_string': 'state_string'
    }

    def __init__(self, braked=None, state=None, state_string=None):  # noqa: E501
        """GetHookBrake - a model defined in Swagger"""  # noqa: E501
        self._braked = None
        self._state = None
        self._state_string = None
        self.discriminator = None
        if braked is not None:
            self.braked = braked
        if state is not None:
            self.state = state
        if state_string is not None:
            self.state_string = state_string

    @property
    def braked(self):
        """Gets the braked of this GetHookBrake.  # noqa: E501

        Whether the brake of the hook is active or not  # noqa: E501

        :return: The braked of this GetHookBrake.  # noqa: E501
        :rtype: bool
        """
        return self._braked

    @braked.setter
    def braked(self, braked):
        """Sets the braked of this GetHookBrake.

        Whether the brake of the hook is active or not  # noqa: E501

        :param braked: The braked of this GetHookBrake.  # noqa: E501
        :type: bool
        """

        self._braked = braked

    @property
    def state(self):
        """Gets the state of this GetHookBrake.  # noqa: E501

        The state of the hook brake in machine format  # noqa: E501

        :return: The state of this GetHookBrake.  # noqa: E501
        :rtype: int
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetHookBrake.

        The state of the hook brake in machine format  # noqa: E501

        :param state: The state of this GetHookBrake.  # noqa: E501
        :type: int
        """

        self._state = state

    @property
    def state_string(self):
        """Gets the state_string of this GetHookBrake.  # noqa: E501

        The state of the hook brake in human format  # noqa: E501

        :return: The state_string of this GetHookBrake.  # noqa: E501
        :rtype: str
        """
        return self._state_string

    @state_string.setter
    def state_string(self, state_string):
        """Sets the state_string of this GetHookBrake.

        The state of the hook brake in human format  # noqa: E501

        :param state_string: The state_string of this GetHookBrake.  # noqa: E501
        :type: str
        """

        self._state_string = state_string

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetHookBrake, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetHookBrake):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
