# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetWifiConnections(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bssid': 'str',
        'connected': 'bool',
        'mac': 'str',
        'name': 'str',
        'url': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'bssid': 'bssid',
        'connected': 'connected',
        'mac': 'mac',
        'name': 'name',
        'url': 'url',
        'uuid': 'uuid'
    }

    def __init__(self, bssid=None, connected=None, mac=None, name=None, url=None, uuid=None):  # noqa: E501
        """GetWifiConnections - a model defined in Swagger"""  # noqa: E501
        self._bssid = None
        self._connected = None
        self._mac = None
        self._name = None
        self._url = None
        self._uuid = None
        self.discriminator = None
        if bssid is not None:
            self.bssid = bssid
        if connected is not None:
            self.connected = connected
        if mac is not None:
            self.mac = mac
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if uuid is not None:
            self.uuid = uuid

    @property
    def bssid(self):
        """Gets the bssid of this GetWifiConnections.  # noqa: E501

        Access point mac address  # noqa: E501

        :return: The bssid of this GetWifiConnections.  # noqa: E501
        :rtype: str
        """
        return self._bssid

    @bssid.setter
    def bssid(self, bssid):
        """Sets the bssid of this GetWifiConnections.

        Access point mac address  # noqa: E501

        :param bssid: The bssid of this GetWifiConnections.  # noqa: E501
        :type: str
        """

        self._bssid = bssid

    @property
    def connected(self):
        """Gets the connected of this GetWifiConnections.  # noqa: E501

        Connected to the network of this connection  # noqa: E501

        :return: The connected of this GetWifiConnections.  # noqa: E501
        :rtype: bool
        """
        return self._connected

    @connected.setter
    def connected(self, connected):
        """Sets the connected of this GetWifiConnections.

        Connected to the network of this connection  # noqa: E501

        :param connected: The connected of this GetWifiConnections.  # noqa: E501
        :type: bool
        """

        self._connected = connected

    @property
    def mac(self):
        """Gets the mac of this GetWifiConnections.  # noqa: E501

        Network adapter mac address  # noqa: E501

        :return: The mac of this GetWifiConnections.  # noqa: E501
        :rtype: str
        """
        return self._mac

    @mac.setter
    def mac(self, mac):
        """Sets the mac of this GetWifiConnections.

        Network adapter mac address  # noqa: E501

        :param mac: The mac of this GetWifiConnections.  # noqa: E501
        :type: str
        """

        self._mac = mac

    @property
    def name(self):
        """Gets the name of this GetWifiConnections.  # noqa: E501

        Name or id of the connection  # noqa: E501

        :return: The name of this GetWifiConnections.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetWifiConnections.

        Name or id of the connection  # noqa: E501

        :param name: The name of this GetWifiConnections.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this GetWifiConnections.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetWifiConnections.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetWifiConnections.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetWifiConnections.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def uuid(self):
        """Gets the uuid of this GetWifiConnections.  # noqa: E501

        Uuid of the connection  # noqa: E501

        :return: The uuid of this GetWifiConnections.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this GetWifiConnections.

        Uuid of the connection  # noqa: E501

        :param uuid: The uuid of this GetWifiConnections.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetWifiConnections, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetWifiConnections):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
