# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetSetting(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'constraints': 'str',
        'default': 'str',
        'description': 'str',
        'fieldtype': 'str',
        'full_name': 'str',
        'id': 'int',
        'name': 'str',
        'parent_id': 'str',
        'parent_name': 'str',
        'parent_value': 'str',
        'select_group': 'int',
        'settings_group': 'str',
        'settings_group_id': 'int',
        'type': 'str',
        'value': 'str'
    }

    attribute_map = {
        'constraints': 'constraints',
        'default': 'default',
        'description': 'description',
        'fieldtype': 'fieldtype',
        'full_name': 'full_name',
        'id': 'id',
        'name': 'name',
        'parent_id': 'parent_id',
        'parent_name': 'parent_name',
        'parent_value': 'parent_value',
        'select_group': 'select_group',
        'settings_group': 'settings_group',
        'settings_group_id': 'settings_group_id',
        'type': 'type',
        'value': 'value'
    }

    def __init__(self, constraints=None, default=None, description=None, fieldtype=None, full_name=None, id=None, name=None, parent_id=None, parent_name=None, parent_value=None, select_group=None, settings_group=None, settings_group_id=None, type=None, value=None):  # noqa: E501
        """GetSetting - a model defined in Swagger"""  # noqa: E501
        self._constraints = None
        self._default = None
        self._description = None
        self._fieldtype = None
        self._full_name = None
        self._id = None
        self._name = None
        self._parent_id = None
        self._parent_name = None
        self._parent_value = None
        self._select_group = None
        self._settings_group = None
        self._settings_group_id = None
        self._type = None
        self._value = None
        self.discriminator = None
        if constraints is not None:
            self.constraints = constraints
        if default is not None:
            self.default = default
        if description is not None:
            self.description = description
        if fieldtype is not None:
            self.fieldtype = fieldtype
        if full_name is not None:
            self.full_name = full_name
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if parent_id is not None:
            self.parent_id = parent_id
        if parent_name is not None:
            self.parent_name = parent_name
        if parent_value is not None:
            self.parent_value = parent_value
        if select_group is not None:
            self.select_group = select_group
        if settings_group is not None:
            self.settings_group = settings_group
        if settings_group_id is not None:
            self.settings_group_id = settings_group_id
        if type is not None:
            self.type = type
        if value is not None:
            self.value = value

    @property
    def constraints(self):
        """Gets the constraints of this GetSetting.  # noqa: E501


        :return: The constraints of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._constraints

    @constraints.setter
    def constraints(self, constraints):
        """Sets the constraints of this GetSetting.


        :param constraints: The constraints of this GetSetting.  # noqa: E501
        :type: str
        """

        self._constraints = constraints

    @property
    def default(self):
        """Gets the default of this GetSetting.  # noqa: E501


        :return: The default of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this GetSetting.


        :param default: The default of this GetSetting.  # noqa: E501
        :type: str
        """

        self._default = default

    @property
    def description(self):
        """Gets the description of this GetSetting.  # noqa: E501


        :return: The description of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GetSetting.


        :param description: The description of this GetSetting.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def fieldtype(self):
        """Gets the fieldtype of this GetSetting.  # noqa: E501


        :return: The fieldtype of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._fieldtype

    @fieldtype.setter
    def fieldtype(self, fieldtype):
        """Sets the fieldtype of this GetSetting.


        :param fieldtype: The fieldtype of this GetSetting.  # noqa: E501
        :type: str
        """

        self._fieldtype = fieldtype

    @property
    def full_name(self):
        """Gets the full_name of this GetSetting.  # noqa: E501


        :return: The full_name of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this GetSetting.


        :param full_name: The full_name of this GetSetting.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def id(self):
        """Gets the id of this GetSetting.  # noqa: E501


        :return: The id of this GetSetting.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetSetting.


        :param id: The id of this GetSetting.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GetSetting.  # noqa: E501


        :return: The name of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GetSetting.


        :param name: The name of this GetSetting.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parent_id(self):
        """Gets the parent_id of this GetSetting.  # noqa: E501


        :return: The parent_id of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this GetSetting.


        :param parent_id: The parent_id of this GetSetting.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def parent_name(self):
        """Gets the parent_name of this GetSetting.  # noqa: E501


        :return: The parent_name of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._parent_name

    @parent_name.setter
    def parent_name(self, parent_name):
        """Sets the parent_name of this GetSetting.


        :param parent_name: The parent_name of this GetSetting.  # noqa: E501
        :type: str
        """

        self._parent_name = parent_name

    @property
    def parent_value(self):
        """Gets the parent_value of this GetSetting.  # noqa: E501


        :return: The parent_value of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._parent_value

    @parent_value.setter
    def parent_value(self, parent_value):
        """Sets the parent_value of this GetSetting.


        :param parent_value: The parent_value of this GetSetting.  # noqa: E501
        :type: str
        """

        self._parent_value = parent_value

    @property
    def select_group(self):
        """Gets the select_group of this GetSetting.  # noqa: E501


        :return: The select_group of this GetSetting.  # noqa: E501
        :rtype: int
        """
        return self._select_group

    @select_group.setter
    def select_group(self, select_group):
        """Sets the select_group of this GetSetting.


        :param select_group: The select_group of this GetSetting.  # noqa: E501
        :type: int
        """

        self._select_group = select_group

    @property
    def settings_group(self):
        """Gets the settings_group of this GetSetting.  # noqa: E501


        :return: The settings_group of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._settings_group

    @settings_group.setter
    def settings_group(self, settings_group):
        """Sets the settings_group of this GetSetting.


        :param settings_group: The settings_group of this GetSetting.  # noqa: E501
        :type: str
        """

        self._settings_group = settings_group

    @property
    def settings_group_id(self):
        """Gets the settings_group_id of this GetSetting.  # noqa: E501


        :return: The settings_group_id of this GetSetting.  # noqa: E501
        :rtype: int
        """
        return self._settings_group_id

    @settings_group_id.setter
    def settings_group_id(self, settings_group_id):
        """Sets the settings_group_id of this GetSetting.


        :param settings_group_id: The settings_group_id of this GetSetting.  # noqa: E501
        :type: int
        """

        self._settings_group_id = settings_group_id

    @property
    def type(self):
        """Gets the type of this GetSetting.  # noqa: E501


        :return: The type of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GetSetting.


        :param type: The type of this GetSetting.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this GetSetting.  # noqa: E501


        :return: The value of this GetSetting.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this GetSetting.


        :param value: The value of this GetSetting.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSetting, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSetting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
