# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetSessionImport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_message': 'str',
        'missions_to_import': 'str',
        'sessions_imported': 'int',
        'sessions_total': 'int',
        'status': 'int'
    }

    attribute_map = {
        'error_message': 'error_message',
        'missions_to_import': 'missions_to_import',
        'sessions_imported': 'sessions_imported',
        'sessions_total': 'sessions_total',
        'status': 'status'
    }

    def __init__(self, error_message=None, missions_to_import=None, sessions_imported=None, sessions_total=None, status=None):  # noqa: E501
        """GetSessionImport - a model defined in Swagger"""  # noqa: E501
        self._error_message = None
        self._missions_to_import = None
        self._sessions_imported = None
        self._sessions_total = None
        self._status = None
        self.discriminator = None
        if error_message is not None:
            self.error_message = error_message
        if missions_to_import is not None:
            self.missions_to_import = missions_to_import
        if sessions_imported is not None:
            self.sessions_imported = sessions_imported
        if sessions_total is not None:
            self.sessions_total = sessions_total
        if status is not None:
            self.status = status

    @property
    def error_message(self):
        """Gets the error_message of this GetSessionImport.  # noqa: E501

        A description of this action  # noqa: E501

        :return: The error_message of this GetSessionImport.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this GetSessionImport.

        A description of this action  # noqa: E501

        :param error_message: The error_message of this GetSessionImport.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def missions_to_import(self):
        """Gets the missions_to_import of this GetSessionImport.  # noqa: E501


        :return: The missions_to_import of this GetSessionImport.  # noqa: E501
        :rtype: str
        """
        return self._missions_to_import

    @missions_to_import.setter
    def missions_to_import(self, missions_to_import):
        """Sets the missions_to_import of this GetSessionImport.


        :param missions_to_import: The missions_to_import of this GetSessionImport.  # noqa: E501
        :type: str
        """

        self._missions_to_import = missions_to_import

    @property
    def sessions_imported(self):
        """Gets the sessions_imported of this GetSessionImport.  # noqa: E501

        The type of area action  # noqa: E501

        :return: The sessions_imported of this GetSessionImport.  # noqa: E501
        :rtype: int
        """
        return self._sessions_imported

    @sessions_imported.setter
    def sessions_imported(self, sessions_imported):
        """Sets the sessions_imported of this GetSessionImport.

        The type of area action  # noqa: E501

        :param sessions_imported: The sessions_imported of this GetSessionImport.  # noqa: E501
        :type: int
        """

        self._sessions_imported = sessions_imported

    @property
    def sessions_total(self):
        """Gets the sessions_total of this GetSessionImport.  # noqa: E501

        A name associated with this area action  # noqa: E501

        :return: The sessions_total of this GetSessionImport.  # noqa: E501
        :rtype: int
        """
        return self._sessions_total

    @sessions_total.setter
    def sessions_total(self, sessions_total):
        """Sets the sessions_total of this GetSessionImport.

        A name associated with this area action  # noqa: E501

        :param sessions_total: The sessions_total of this GetSessionImport.  # noqa: E501
        :type: int
        """

        self._sessions_total = sessions_total

    @property
    def status(self):
        """Gets the status of this GetSessionImport.  # noqa: E501

        A nice name associated with this area action  # noqa: E501

        :return: The status of this GetSessionImport.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GetSessionImport.

        A nice name associated with this area action  # noqa: E501

        :param status: The status of this GetSessionImport.  # noqa: E501
        :type: int
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSessionImport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSessionImport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
