# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PostWorldModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'robot_ip': 'str',
        'world_model': 'list[object]'
    }

    attribute_map = {
        'robot_ip': 'robot_ip',
        'world_model': 'world_model'
    }

    def __init__(self, robot_ip=None, world_model=None):  # noqa: E501
        """PostWorldModel - a model defined in Swagger"""  # noqa: E501
        self._robot_ip = None
        self._world_model = None
        self.discriminator = None
        if robot_ip is not None:
            self.robot_ip = robot_ip
        if world_model is not None:
            self.world_model = world_model

    @property
    def robot_ip(self):
        """Gets the robot_ip of this PostWorldModel.  # noqa: E501


        :return: The robot_ip of this PostWorldModel.  # noqa: E501
        :rtype: str
        """
        return self._robot_ip

    @robot_ip.setter
    def robot_ip(self, robot_ip):
        """Sets the robot_ip of this PostWorldModel.


        :param robot_ip: The robot_ip of this PostWorldModel.  # noqa: E501
        :type: str
        """

        self._robot_ip = robot_ip

    @property
    def world_model(self):
        """Gets the world_model of this PostWorldModel.  # noqa: E501


        :return: The world_model of this PostWorldModel.  # noqa: E501
        :rtype: list[object]
        """
        return self._world_model

    @world_model.setter
    def world_model(self, world_model):
        """Sets the world_model of this PostWorldModel.


        :param world_model: The world_model of this PostWorldModel.  # noqa: E501
        :type: list[object]
        """

        self._world_model = world_model

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostWorldModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostWorldModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
