# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PostCartCalibrations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_by_id': 'str',
        'drive_height': 'int',
        'entry_height': 'int',
        'guid': 'str',
        'lock_height': 'int',
        'name': 'str',
        'qw': 'float',
        'qx': 'float',
        'qy': 'float',
        'qz': 'float',
        'standard': 'bool',
        'x': 'float',
        'y': 'float',
        'z': 'float'
    }

    attribute_map = {
        'created_by_id': 'created_by_id',
        'drive_height': 'drive_height',
        'entry_height': 'entry_height',
        'guid': 'guid',
        'lock_height': 'lock_height',
        'name': 'name',
        'qw': 'qw',
        'qx': 'qx',
        'qy': 'qy',
        'qz': 'qz',
        'standard': 'standard',
        'x': 'x',
        'y': 'y',
        'z': 'z'
    }

    def __init__(self, created_by_id=None, drive_height=None, entry_height=None, guid=None, lock_height=None, name=None, qw=None, qx=None, qy=None, qz=None, standard=None, x=None, y=None, z=None):  # noqa: E501
        """PostCartCalibrations - a model defined in Swagger"""  # noqa: E501
        self._created_by_id = None
        self._drive_height = None
        self._entry_height = None
        self._guid = None
        self._lock_height = None
        self._name = None
        self._qw = None
        self._qx = None
        self._qy = None
        self._qz = None
        self._standard = None
        self._x = None
        self._y = None
        self._z = None
        self.discriminator = None
        if created_by_id is not None:
            self.created_by_id = created_by_id
        self.drive_height = drive_height
        self.entry_height = entry_height
        if guid is not None:
            self.guid = guid
        self.lock_height = lock_height
        self.name = name
        self.qw = qw
        self.qx = qx
        self.qy = qy
        self.qz = qz
        self.standard = standard
        self.x = x
        self.y = y
        self.z = z

    @property
    def created_by_id(self):
        """Gets the created_by_id of this PostCartCalibrations.  # noqa: E501


        :return: The created_by_id of this PostCartCalibrations.  # noqa: E501
        :rtype: str
        """
        return self._created_by_id

    @created_by_id.setter
    def created_by_id(self, created_by_id):
        """Sets the created_by_id of this PostCartCalibrations.


        :param created_by_id: The created_by_id of this PostCartCalibrations.  # noqa: E501
        :type: str
        """

        self._created_by_id = created_by_id

    @property
    def drive_height(self):
        """Gets the drive_height of this PostCartCalibrations.  # noqa: E501


        :return: The drive_height of this PostCartCalibrations.  # noqa: E501
        :rtype: int
        """
        return self._drive_height

    @drive_height.setter
    def drive_height(self, drive_height):
        """Sets the drive_height of this PostCartCalibrations.


        :param drive_height: The drive_height of this PostCartCalibrations.  # noqa: E501
        :type: int
        """
        if drive_height is None:
            raise ValueError("Invalid value for `drive_height`, must not be `None`")  # noqa: E501

        self._drive_height = drive_height

    @property
    def entry_height(self):
        """Gets the entry_height of this PostCartCalibrations.  # noqa: E501


        :return: The entry_height of this PostCartCalibrations.  # noqa: E501
        :rtype: int
        """
        return self._entry_height

    @entry_height.setter
    def entry_height(self, entry_height):
        """Sets the entry_height of this PostCartCalibrations.


        :param entry_height: The entry_height of this PostCartCalibrations.  # noqa: E501
        :type: int
        """
        if entry_height is None:
            raise ValueError("Invalid value for `entry_height`, must not be `None`")  # noqa: E501

        self._entry_height = entry_height

    @property
    def guid(self):
        """Gets the guid of this PostCartCalibrations.  # noqa: E501


        :return: The guid of this PostCartCalibrations.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this PostCartCalibrations.


        :param guid: The guid of this PostCartCalibrations.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def lock_height(self):
        """Gets the lock_height of this PostCartCalibrations.  # noqa: E501


        :return: The lock_height of this PostCartCalibrations.  # noqa: E501
        :rtype: int
        """
        return self._lock_height

    @lock_height.setter
    def lock_height(self, lock_height):
        """Sets the lock_height of this PostCartCalibrations.


        :param lock_height: The lock_height of this PostCartCalibrations.  # noqa: E501
        :type: int
        """
        if lock_height is None:
            raise ValueError("Invalid value for `lock_height`, must not be `None`")  # noqa: E501

        self._lock_height = lock_height

    @property
    def name(self):
        """Gets the name of this PostCartCalibrations.  # noqa: E501

        Min length: 1, Max length: 40  # noqa: E501

        :return: The name of this PostCartCalibrations.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PostCartCalibrations.

        Min length: 1, Max length: 40  # noqa: E501

        :param name: The name of this PostCartCalibrations.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def qw(self):
        """Gets the qw of this PostCartCalibrations.  # noqa: E501


        :return: The qw of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._qw

    @qw.setter
    def qw(self, qw):
        """Sets the qw of this PostCartCalibrations.


        :param qw: The qw of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if qw is None:
            raise ValueError("Invalid value for `qw`, must not be `None`")  # noqa: E501

        self._qw = qw

    @property
    def qx(self):
        """Gets the qx of this PostCartCalibrations.  # noqa: E501


        :return: The qx of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._qx

    @qx.setter
    def qx(self, qx):
        """Sets the qx of this PostCartCalibrations.


        :param qx: The qx of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if qx is None:
            raise ValueError("Invalid value for `qx`, must not be `None`")  # noqa: E501

        self._qx = qx

    @property
    def qy(self):
        """Gets the qy of this PostCartCalibrations.  # noqa: E501


        :return: The qy of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._qy

    @qy.setter
    def qy(self, qy):
        """Sets the qy of this PostCartCalibrations.


        :param qy: The qy of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if qy is None:
            raise ValueError("Invalid value for `qy`, must not be `None`")  # noqa: E501

        self._qy = qy

    @property
    def qz(self):
        """Gets the qz of this PostCartCalibrations.  # noqa: E501


        :return: The qz of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._qz

    @qz.setter
    def qz(self, qz):
        """Sets the qz of this PostCartCalibrations.


        :param qz: The qz of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if qz is None:
            raise ValueError("Invalid value for `qz`, must not be `None`")  # noqa: E501

        self._qz = qz

    @property
    def standard(self):
        """Gets the standard of this PostCartCalibrations.  # noqa: E501


        :return: The standard of this PostCartCalibrations.  # noqa: E501
        :rtype: bool
        """
        return self._standard

    @standard.setter
    def standard(self, standard):
        """Sets the standard of this PostCartCalibrations.


        :param standard: The standard of this PostCartCalibrations.  # noqa: E501
        :type: bool
        """
        if standard is None:
            raise ValueError("Invalid value for `standard`, must not be `None`")  # noqa: E501

        self._standard = standard

    @property
    def x(self):
        """Gets the x of this PostCartCalibrations.  # noqa: E501


        :return: The x of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this PostCartCalibrations.


        :param x: The x of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self):
        """Gets the y of this PostCartCalibrations.  # noqa: E501


        :return: The y of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this PostCartCalibrations.


        :param y: The y of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def z(self):
        """Gets the z of this PostCartCalibrations.  # noqa: E501


        :return: The z of this PostCartCalibrations.  # noqa: E501
        :rtype: float
        """
        return self._z

    @z.setter
    def z(self, z):
        """Sets the z of this PostCartCalibrations.


        :param z: The z of this PostCartCalibrations.  # noqa: E501
        :type: float
        """
        if z is None:
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501

        self._z = z

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostCartCalibrations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostCartCalibrations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
