# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PostRobots(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'robots': 'list[object]'
    }

    attribute_map = {
        'robots': 'robots'
    }

    def __init__(self, robots=None):  # noqa: E501
        """PostRobots - a model defined in Swagger"""  # noqa: E501
        self._robots = None
        self.discriminator = None
        self.robots = robots

    @property
    def robots(self):
        """Gets the robots of this PostRobots.  # noqa: E501


        :return: The robots of this PostRobots.  # noqa: E501
        :rtype: list[object]
        """
        return self._robots

    @robots.setter
    def robots(self, robots):
        """Sets the robots of this PostRobots.


        :param robots: The robots of this PostRobots.  # noqa: E501
        :type: list[object]
        """
        if robots is None:
            raise ValueError("Invalid value for `robots`, must not be `None`")  # noqa: E501

        self._robots = robots

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostRobots, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostRobots):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
