# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PutCart(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cart_calibration_id': 'str',
        'cart_type_id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'cart_calibration_id': 'cart_calibration_id',
        'cart_type_id': 'cart_type_id',
        'name': 'name'
    }

    def __init__(self, cart_calibration_id=None, cart_type_id=None, name=None):  # noqa: E501
        """PutCart - a model defined in Swagger"""  # noqa: E501
        self._cart_calibration_id = None
        self._cart_type_id = None
        self._name = None
        self.discriminator = None
        if cart_calibration_id is not None:
            self.cart_calibration_id = cart_calibration_id
        if cart_type_id is not None:
            self.cart_type_id = cart_type_id
        if name is not None:
            self.name = name

    @property
    def cart_calibration_id(self):
        """Gets the cart_calibration_id of this PutCart.  # noqa: E501


        :return: The cart_calibration_id of this PutCart.  # noqa: E501
        :rtype: str
        """
        return self._cart_calibration_id

    @cart_calibration_id.setter
    def cart_calibration_id(self, cart_calibration_id):
        """Sets the cart_calibration_id of this PutCart.


        :param cart_calibration_id: The cart_calibration_id of this PutCart.  # noqa: E501
        :type: str
        """

        self._cart_calibration_id = cart_calibration_id

    @property
    def cart_type_id(self):
        """Gets the cart_type_id of this PutCart.  # noqa: E501


        :return: The cart_type_id of this PutCart.  # noqa: E501
        :rtype: str
        """
        return self._cart_type_id

    @cart_type_id.setter
    def cart_type_id(self, cart_type_id):
        """Sets the cart_type_id of this PutCart.


        :param cart_type_id: The cart_type_id of this PutCart.  # noqa: E501
        :type: str
        """

        self._cart_type_id = cart_type_id

    @property
    def name(self):
        """Gets the name of this PutCart.  # noqa: E501

        Min length: 1, Max length: 40  # noqa: E501

        :return: The name of this PutCart.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PutCart.

        Min length: 1, Max length: 40  # noqa: E501

        :param name: The name of this PutCart.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutCart, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutCart):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
