# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PutBluetoothRelay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hardware_id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'hardware_id': 'hardware_id',
        'name': 'name'
    }

    def __init__(self, hardware_id=None, name=None):  # noqa: E501
        """PutBluetoothRelay - a model defined in Swagger"""  # noqa: E501
        self._hardware_id = None
        self._name = None
        self.discriminator = None
        if hardware_id is not None:
            self.hardware_id = hardware_id
        if name is not None:
            self.name = name

    @property
    def hardware_id(self):
        """Gets the hardware_id of this PutBluetoothRelay.  # noqa: E501


        :return: The hardware_id of this PutBluetoothRelay.  # noqa: E501
        :rtype: str
        """
        return self._hardware_id

    @hardware_id.setter
    def hardware_id(self, hardware_id):
        """Sets the hardware_id of this PutBluetoothRelay.


        :param hardware_id: The hardware_id of this PutBluetoothRelay.  # noqa: E501
        :type: str
        """

        self._hardware_id = hardware_id

    @property
    def name(self):
        """Gets the name of this PutBluetoothRelay.  # noqa: E501

        Min length: 1, Max length: 255  # noqa: E501

        :return: The name of this PutBluetoothRelay.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PutBluetoothRelay.

        Min length: 1, Max length: 255  # noqa: E501

        :param name: The name of this PutBluetoothRelay.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutBluetoothRelay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutBluetoothRelay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
