# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PutModbusMission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'coil_id': 'int',
        'mission_id': 'str',
        'name': 'str',
        'parameters': 'list[object]'
    }

    attribute_map = {
        'coil_id': 'coil_id',
        'mission_id': 'mission_id',
        'name': 'name',
        'parameters': 'parameters'
    }

    def __init__(self, coil_id=None, mission_id=None, name=None, parameters=None):  # noqa: E501
        """PutModbusMission - a model defined in Swagger"""  # noqa: E501
        self._coil_id = None
        self._mission_id = None
        self._name = None
        self._parameters = None
        self.discriminator = None
        if coil_id is not None:
            self.coil_id = coil_id
        if mission_id is not None:
            self.mission_id = mission_id
        if name is not None:
            self.name = name
        if parameters is not None:
            self.parameters = parameters

    @property
    def coil_id(self):
        """Gets the coil_id of this PutModbusMission.  # noqa: E501


        :return: The coil_id of this PutModbusMission.  # noqa: E501
        :rtype: int
        """
        return self._coil_id

    @coil_id.setter
    def coil_id(self, coil_id):
        """Sets the coil_id of this PutModbusMission.


        :param coil_id: The coil_id of this PutModbusMission.  # noqa: E501
        :type: int
        """

        self._coil_id = coil_id

    @property
    def mission_id(self):
        """Gets the mission_id of this PutModbusMission.  # noqa: E501


        :return: The mission_id of this PutModbusMission.  # noqa: E501
        :rtype: str
        """
        return self._mission_id

    @mission_id.setter
    def mission_id(self, mission_id):
        """Sets the mission_id of this PutModbusMission.


        :param mission_id: The mission_id of this PutModbusMission.  # noqa: E501
        :type: str
        """

        self._mission_id = mission_id

    @property
    def name(self):
        """Gets the name of this PutModbusMission.  # noqa: E501

        Min length: 1, Max length: 200  # noqa: E501

        :return: The name of this PutModbusMission.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PutModbusMission.

        Min length: 1, Max length: 200  # noqa: E501

        :param name: The name of this PutModbusMission.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parameters(self):
        """Gets the parameters of this PutModbusMission.  # noqa: E501


        :return: The parameters of this PutModbusMission.  # noqa: E501
        :rtype: list[object]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this PutModbusMission.


        :param parameters: The parameters of this PutModbusMission.  # noqa: E501
        :type: list[object]
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutModbusMission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutModbusMission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
